In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

movies = pd.read_csv("Data/movies.csv")
ratings = pd.read_csv("Data/ratings.csv")

In [2]:
df = ratings.merge(movies, on="movieId")

In [3]:
movie_stats = df.groupby("title").agg(
    avg_rating=("rating", "mean"),
    num_ratings=("rating", "count")
)

movie_stats.head()

                                         avg_rating  num_ratings
title
'71 (2014)                                      4.0            1
'Hellboy': The Seeds of Creation (2004)         4.0            1
'Round Midnight (1986)                          3.5            2
'Salem's Lot (2004)                             5.0            1
'Til There Was You (1997)                       4.0            2

In [4]:
movie_stats.sort_values("num_ratings", ascending=False).head(10)

                                           avg_rating  num_ratings
title
Forrest Gump (1994)                          4.164134          329
Shawshank Redemption, The (1994)             4.429022          317
Pulp Fiction (1994)                          4.197068          307
Silence of the Lambs, The (1991)             4.161290          279
Matrix, The (1999)                           4.192446          278
Star Wars: Episode IV - A New Hope (1977)    4.231076          251
Jurassic Park (1993)                         3.750000          238
Braveheart (1995)                            4.031646          237
Terminator 2: Judgment Day (1991)            3.970982          224
Schindler's List (1993)                      4.225000          220

In [5]:
movie_stats[movie_stats["num_ratings"] >= 50] \
    .sort_values("avg_rating", ascending=False) \
    .head(10)

                                                    avg_rating  num_ratings
title
Shawshank Redemption, The (1994)                      4.429022          317
Godfather, The (1972)                                 4.289062          192
Fight Club (1999)                                     4.272936          218
Cool Hand Luke (1967)                                 4.271930           57
Dr. Strangelove or: How I Learned to Stop Worry...    4.268041           97
Rear Window (1954)                                    4.261905           84
Godfather: Part II, The (1974)                        4.259690          129
Departed, The (2006)                                  4.252336          107
Goodfellas (1990)                                     4.250000          126
Casablanca (1942)                                     4.240000          100

In [6]:
movie_stats = df.groupby('title').agg(
    average_rating=('rating', 'mean'),
    number_of_ratings=('rating', 'count')
)

movie_stats.head()

                                         average_rating  number_of_ratings
title
'71 (2014)                                          4.0                  1
'Hellboy': The Seeds of Creation (2004)             4.0                  1
'Round Midnight (1986)                              3.5                  2
'Salem's Lot (2004)                                 5.0                  1
'Til There Was You (1997)                           4.0                  2

In [7]:
movie_stats.sort_values(
    'number_of_ratings',
    ascending=False
).head(20)

,average_rating,number_of_ratings
title,,
Forrest Gump (1994),4.164134,329
"Shawshank Redemption, The (1994)",4.429022,317
Pulp Fiction (1994),4.197068,307
"Silence of the Lambs, The (1991)",4.161290,279
"Matrix, The (1999)",4.192446,278
Star Wars: Episode IV - A New Hope (1977),4.231076,251
Jurassic Park (1993),3.750000,238
Braveheart (1995),4.031646,237
Terminator 2: Judgment Day (1991),3.970982,224
Schindler's List (1993),4.225000,220
Fight Club (1999),4.272936,218
Toy Story (1995),3.920930,215
Star Wars: Episode V - The Empire Strikes Back (1980),4.215640,211
"Usual Suspects, The (1995)",4.237745,204
American Beauty (1999),4.056373,204
Seven (a.k.a. Se7en) (1995),3.975369,203
Independence Day (a.k.a. ID4) (1996),3.445545,202
Apollo 13 (1995),3.845771,201
Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark) (1981),4.207500,200
"Lord of the Rings: The Fellowship of the Ring, The (2001)",4.106061,198

In [8]:
movie_stats[
    movie_stats['number_of_ratings'] > 100
].sort_values(
    'average_rating',
    ascending=False
).head(20)

,average_rating,number_of_ratings
title,,
"Shawshank Redemption, The (1994)",4.429022,317
"Godfather, The (1972)",4.289062,192
Fight Club (1999),4.272936,218
"Godfather: Part II, The (1974)",4.259690,129
"Departed, The (2006)",4.252336,107
Goodfellas (1990),4.250000,126
"Dark Knight, The (2008)",4.238255,149
"Usual Suspects, The (1995)",4.237745,204
"Princess Bride, The (1987)",4.232394,142
Star Wars: Episode IV - A New Hope (1977),4.231076,251
Schindler's List (1993),4.225000,220
Apocalypse Now (1979),4.219626,107
American History X (1998),4.217054,129
Star Wars: Episode V - The Empire Strikes Back (1980),4.215640,211
Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark) (1981),4.207500,200
One Flew Over the Cuckoo's Nest (1975),4.203008,133
Reservoir Dogs (1992),4.202290,131
Pulp Fiction (1994),4.197068,307
"Matrix, The (1999)",4.192446,278
"Amelie (Fabuleux destin d'Amélie Poulain, Le) (2001)",4.183333,120

In [9]:
user_movie = df.pivot_table(
    index='userId',
    columns='title',
    values='rating'
)

In [10]:
movie_stats.sort_values(
    'number_of_ratings',
    ascending=False
).head(10)

                                           average_rating  number_of_ratings
title
Forrest Gump (1994)                              4.164134                329
Shawshank Redemption, The (1994)                 4.429022                317
Pulp Fiction (1994)                              4.197068                307
Silence of the Lambs, The (1991)                 4.161290                279
Matrix, The (1999)                               4.192446                278
Star Wars: Episode IV - A New Hope (1977)        4.231076                251
Jurassic Park (1993)                             3.750000                238
Braveheart (1995)                                4.031646                237
Terminator 2: Judgment Day (1991)                3.970982                224
Schindler's List (1993)                          4.225000                220

In [11]:
user_movie_filled = user_movie.fillna(0)

In [12]:
user_movie_filled.head()

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
from sklearn.metrics.pairwise import cosine_similarity

In [14]:
user_similarity = cosine_similarity(user_movie_filled)

In [15]:
user_similarity_df = pd.DataFrame(
    user_similarity,
    index=user_movie_filled.index,
    columns=user_movie_filled.index
)

In [16]:
import pickle

with open("user_movie.pkl", "wb") as f:
    pickle.dump(user_movie, f)

with open("user_similarity.pkl", "wb") as f:
    pickle.dump(user_similarity_df, f)

In [17]:
user_similarity_df.head()

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
userId,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.027283,0.059720,0.194395,0.129080,0.128152,0.158744,0.136968,0.064263,0.016875,...,0.080554,0.164455,0.221486,0.070669,0.153625,0.164191,0.269389,0.291097,0.093572,0.145321
2,0.027283,1.000000,0.000000,0.003726,0.016614,0.025333,0.027585,0.027257,0.000000,0.067445,...,0.202671,0.016866,0.011997,0.000000,0.000000,0.028429,0.012948,0.046211,0.027565,0.102427
3,0.059720,0.000000,1.000000,0.002251,0.005020,0.003936,0.000000,0.004941,0.000000,0.000000,...,0.005048,0.004892,0.024992,0.000000,0.010694,0.012993,0.019247,0.021128,0.000000,0.032119
4,0.194395,0.003726,0.002251,1.000000,0.128659,0.088491,0.115120,0.062969,0.011361,0.031163,...,0.085938,0.128273,0.307973,0.052985,0.084584,0.200395,0.131746,0.149858,0.032198,0.107683
5,0.129080,0.016614,0.005020,0.128659,1.000000,0.300349,0.108342,0.429075,0.000000,0.030611,...,0.068048,0.418747,0.110148,0.258773,0.148758,0.106435,0.152866,0.135535,0.261232,0.060792

In [18]:
similar_users = user_similarity_df.loc[1].sort_values(ascending=False)
similar_users.head(10)

userId
1      1.000000
266    0.357408
313    0.351562
368    0.345127
57     0.345034
91     0.334727
469    0.330664
39     0.329782
288    0.329700
452    0.328048
Name: 1, dtype: float64

In [19]:
similar_users = similar_users.iloc[1:]

In [20]:
top_users = similar_users.head(10)
top_users

userId
266    0.357408
313    0.351562
368    0.345127
57     0.345034
91     0.334727
469    0.330664
39     0.329782
288    0.329700
452    0.328048
45     0.327922
Name: 1, dtype: float64

In [21]:
top_users_ratings = user_movie.loc[top_users.index]

In [22]:
top_users_ratings.head()

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN
91,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
weighted_ratings = top_users_ratings.T.dot(top_users)

In [24]:
weighted_ratings = weighted_ratings / top_users.sum()

In [25]:
watched = user_movie.loc[1].dropna().index

In [26]:
recommendations = weighted_ratings.drop(watched)

In [27]:
recommendations.sort_values(ascending=False).head(10)

title
Terminator 2: Judgment Day (1991)          4.195979
Hunt for Red October, The (1990)           3.957980
2001: A Space Odyssey (1968)               3.855366
Die Hard (1988)                            3.805436
Breakfast Club, The (1985)                 3.574258
'71 (2014)                                      NaN
'Hellboy': The Seeds of Creation (2004)         NaN
'Round Midnight (1986)                          NaN
'Salem's Lot (2004)                             NaN
'Til There Was You (1997)                       NaN
dtype: float64

In [28]:
def recommend_movies(user_id, k=10, n=10):
    # Similar users
    similar_users = user_similarity_df.loc[user_id].drop(user_id)
    similar_users = similar_users.sort_values(ascending=False).head(k)

    # Ratings of similar users
    top_users_ratings = user_movie.loc[similar_users.index]

    # Weighted average
    weighted_ratings = top_users_ratings.T.dot(similar_users)
    weighted_ratings = weighted_ratings / similar_users.sum()

    # Remove already watched movies
    watched = user_movie.loc[user_id].dropna().index
    recommendations = weighted_ratings.drop(watched)

    # Return top recommendations
    return recommendations.sort_values(ascending=False).head(n)

In [29]:
recommend_movies(1)

title
Terminator 2: Judgment Day (1991)          4.195979
Hunt for Red October, The (1990)           3.957980
2001: A Space Odyssey (1968)               3.855366
Die Hard (1988)                            3.805436
Breakfast Club, The (1985)                 3.574258
'71 (2014)                                      NaN
'Hellboy': The Seeds of Creation (2004)         NaN
'Round Midnight (1986)                          NaN
'Salem's Lot (2004)                             NaN
'Til There Was You (1997)                       NaN
dtype: float64

In [30]:
user_similarity_df.loc[1].sort_values(ascending=False).head(10)

userId
1      1.000000
266    0.357408
313    0.351562
368    0.345127
57     0.345034
91     0.334727
469    0.330664
39     0.329782
288    0.329700
452    0.328048
Name: 1, dtype: float64

In [31]:
recommend_movies(1)

title
Terminator 2: Judgment Day (1991)          4.195979
Hunt for Red October, The (1990)           3.957980
2001: A Space Odyssey (1968)               3.855366
Die Hard (1988)                            3.805436
Breakfast Club, The (1985)                 3.574258
'71 (2014)                                      NaN
'Hellboy': The Seeds of Creation (2004)         NaN
'Round Midnight (1986)                          NaN
'Salem's Lot (2004)                             NaN
'Til There Was You (1997)                       NaN
dtype: float64

In [32]:
recommendations = recommendations.dropna()

In [33]:
def recommend_movies(user_id, k=20, n=10, min_ratings=3):

    if user_id not in user_movie.index:
        return None

    similar_users = (
        user_similarity_df.loc[user_id]
        .drop(user_id)
        .sort_values(ascending=False)
        .head(k)
    )

    top_users_ratings = user_movie.loc[similar_users.index].fillna(0)

    weighted_ratings = top_users_ratings.T.dot(similar_users)
    weighted_ratings = weighted_ratings / similar_users.sum()

    watched = user_movie.loc[user_id].dropna().index

    recommendations = weighted_ratings.drop(watched)
    recommendations = recommendations.dropna()

    rating_counts = top_users_ratings.notna().sum()

    filtered = recommendations[
        rating_counts[recommendations.index] >= min_ratings
    ]

    # If filtering removes everything,
    # return the unfiltered recommendations.
    if len(filtered) == 0:
        filtered = recommendations

    return filtered.sort_values(ascending=False).head(n)

In [34]:
recommend_movies(1)

title
Terminator 2: Judgment Day (1991)    3.980596
Aliens (1986)                        3.868938
Sixth Sense, The (1999)              3.789754
Godfather, The (1972)                3.696217
Jaws (1975)                          3.667106
Breakfast Club, The (1985)           3.484794
Die Hard (1988)                      3.459002
Hunt for Red October, The (1990)     3.424283
Ferris Bueller's Day Off (1986)      3.163541
Christmas Story, A (1983)            3.124841
dtype: float64

In [35]:
recommend_movies(6)

title
Demolition Man (1993)                     2.445629
Mission: Impossible (1996)                2.203866
Beverly Hills Cop III (1994)              2.136418
Clueless (1995)                           2.131190
Quiz Show (1994)                          1.952453
Nightmare Before Christmas, The (1993)    1.857445
Toy Story (1995)                          1.849030
Pocahontas (1995)                         1.679975
Home Alone (1990)                         1.603499
Judge Dredd (1995)                        1.391185
dtype: float64